spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/paraustudb
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Siber Güvenlik - Veritabanı Şifreleme Anahtarı (16 byte / 16 karakter)
app.security.encryption.key=MySecretKey12345