spring.application.name=backend

# H2 Database (Geliştirme için en kolayı, kurulum gerektirmez)
spring.datasource.url=jdbc:h2:mem:paraustudb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# PostgreSQL (Gerçek sunucu için - Lazım olduğunda burayı açarsınız)
# spring.datasource.url=jdbc:postgresql://localhost:5432/paraustudb
# spring.datasource.username=postgres
# spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true