# PostgreSQL Bağlantı Bilgileri
# localhost:5432 standarttır, 'paraustudb' kısmını veritabanı adınla değiştir
spring.datasource.url=jdbc:postgresql://localhost:5432/paraustudb
spring.datasource.username=postgres
spring.datasource.password=sifren_buraya  # Kendi PostgreSQL şifreni yaz

# Hibernate & JPA Ayarları
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect